### ISSUE TITLE
Are there any plans for publishing to nuget

### ISSUE THREAD

**Issue by cleftheris** [Crypt32/Asn1DerParser.NET#3]
Hi and thanks for sharing! This is a missing block in dotnet and I was wondering if you could make available a package on nuget org. I searched for the package id "SysadminsLV.Asn1Parser" but nothing came up.

Thanks

**Comment by Crypt32** [comment]
Not yet. The project is not yet complete, various features are not yet implemented. I don't see much value in having this library in the current state on NuGet.

**Comment by cleftheris** [comment]
Thanks for the quick reply!
